# Generated by Django 6.0.7 on 2026-07-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề Banner')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mô tả ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị?')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bản tin')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá bán')),
                ('discount', models.IntegerField(default=0, verbose_name='Giảm giá (%)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Đã bán')),
                ('origin', models.CharField(default='Việt Nam', max_length=50, verbose_name='Xuất xứ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Còn hàng?')),
            ],
        ),
    ]
